apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: linds-postgresql
  namespace: postgresql-linds
  annotations:
    nfs.io/storage-path: "postgresql-nfs"
spec:
  teamId: "linds"
  volume:
    size: 1Gi
    storageClass: nfs-client
  numberOfInstances: 2
  users:
    lindrea_user:  # database owner
    - superuser
    - createdb
    zabbix:
    - superuser
    catcrawl:
    - superuser
  databases:
    lindrea: lindrea_user     # dbname: owner
    lindrea_th: lindrea_user  # dbname: owner
    zabbix: zabbix
    catcrawl: catcrawl
  postgresql:
    version: "14"
  enableShmVolume: true
  patroni:
    pg_hba:
      - "local  all,replication all trust"
      - "host all,replication all 0.0.0.0/0 trust"