apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
      errors
      health {
        lameduck 5s
      }
      ready
      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
      }
      prometheus :9153
      forward . /etc/resolv.conf {
        max_concurrent 1000
      }
      cache 300
      loop
      reload
      loadbalance
      }
    }
    linds.com.au:53 {
      errors
      cache 300
      forward . 10.0.50.1 192.168.6.1 10.3.1.200 10.0.50.200
    }