apiVersion: v1
kind: PersistentVolume
metadata:
  name: linds-nfs
  labels:
    storage.k8s.io/name: nfs
    storage.k8s.io/part-of: kubernetes-complete-reference
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: "manual"
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  nfs:
    server: jd-truenas-01.linds.com.au
    path: /mnt/NAS/NAS
    readOnly: false
---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: linds-nfs-pvc
    namespace: default
  spec:
    storageClassName: "manual"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linds-docker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v1
      name: linds-docker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: v1
        name: linds-docker
    spec:
      containers:
        - name: jacket
          image: linuxserver/jackett:latest
          imagePullPolicy: Always
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: linds-nfs-pvc
              subPath: jackett
          ports:
            - containerPort: 9117
        - name: radarr
          env:
            - name: GUID
              value: "0"
            - name: PUID
              value: "1000"
          image: linuxserver/radarr:latest
          imagePullPolicy: Always
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: linds-nfs-pvc
              subPath: radarr
          ports:
            - containerPort: 7878
        - name: sonarr
          env:
            - name: GUID
              value: "0"
            - name: PUID
              value: "1000"
            - name: SONARR_BRANCH
              value: main
          image: linuxserver/sonarr:latest
          imagePullPolicy: Always
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: linds-nfs-pvc
              subPath: sonarr
          ports:
            - containerPort: 8989
      restartPolicy: Always
      volumes:
        - name: linds-nfs-pvc
          persistentVolumeClaim:
            claimName: linds-nfs-pvc
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: linds-docker
  labels:
    app: linds-docker
spec:
  ports:
  - port: 8989
    targetPort: 8989
    protocol: TCP
    name: sonarr-service
  - port: 9117
    targetPort: 9117
    protocol: TCP
    name: jackett-service
  - port: 7878
    targetPort: 7878
    protocol: TCP
    name: radarr-service
  selector:
    name: linds-docker
