apiVersion: v1
kind: PersistentVolume
metadata:
  name: jd-nfs-truenas
  namespace: default
  labels:
    storage.k8s.io/name: nfs
    storage.k8s.io/part-of: kubernetes-complete-reference
    volume.beta.kubernetes.io/mount-options: soft
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: "manual"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    server: jd-truenas-01.linds.com.au
    path: /mnt/NAS/NAS
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jd-nfs-pvc
  namespace: default
spec:
  storageClassName: "manual"
  volumeName: jd-nfs-truenas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
  namespace: default
spec:
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
      annotations:
        diun.enable: "true"
    spec:
      containers:
      - name: factorio
        image: factoriotools/factorio:stable
        imagePullPolicy: Always
        ports:
        - containerPort: 34197
          protocol: UDP
        - containerPort: 27015
        volumeMounts:
        - mountPath: /factorio
          name: jd-nfs-pvc
          subPath: factorio
        env:
          - name: CONFIG
            value: /factorio/config
          - name: PORT
            value: "34197"
          - name: RCON_PORT
            value: "27015"
          - name: PUID
            value: "845"
          - name: PGID
            value: "845"
      volumes:
        - name: jd-nfs-pvc
          persistentVolumeClaim:
            claimName: jd-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: factorio
  annotations:
    metallb.universe.tf/address-pool: jd-bgp-pool
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: factorio
  ports:
  - port: 34197
    targetPort: 34197
    protocol: UDP
    name: factorio-udp
  - port: 27015
    targetPort: 27015
    protocol: TCP
    name: factorio-tcp
