apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: jd-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.53.11-10.0.53.200
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: jd-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - jd-ip-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: jd-bgp-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.16.10.1-172.16.10.254
  - 172.16.11.1-172.16.11.254
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: jd-bgp-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - jd-bgp-pool
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: jd-bgp-peer
  namespace: metallb-system
spec:
  myASN: 64500
  peerASN: 64550
  peerAddress: 10.0.50.1
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: linds-bgp-peer
  namespace: metallb-system
spec:
  myASN: 64500
  peerASN: 64551
  peerAddress: 192.168.6.1
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: linds-bgp-peer
  namespace: metallb-system
spec:
  myASN: 64500
  peerASN: 64551
  peerAddress: 10.3.1.1