---
apiVersion: v1
kind: Namespace
metadata:
  name: unifi
  labels:
    name: home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jd-nfs-pvc-unifi
  namespace: unifi
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: unifi
  namespace: unifi
spec:
  serviceName: "unifi"
  replicas: 1
  selector:
    matchLabels:
      name: unifi
  template:
    metadata:
      name: unifi
      labels:
        name: unifi
      annotations:
        diun.enable: "true"
    spec:
      containers:
        - name: unifi
          image: lscr.io/linuxserver/unifi-network-application:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3478
              protocol: UDP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8843
              protocol: TCP
            - containerPort: 8880
              protocol: TCP
            - containerPort: 6789
              protocol: TCP
          volumeMounts:
            - name: jd-nfs-pvc-unifi
              mountPath: /config
              subPath: unifi-appliance
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: MONGO_HOST
              value: localhost
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              valueFrom:
                configMapKeyRef:
                  name: unifi-mongo-secret
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                configMapKeyRef:
                  name: unifi-mongo-secret
                  key: MONGO_PASS
            - name: MONGO_DBNAME
              value: unifi
        - name: mongodb
          image: registry.hub.docker.com/library/mongo:4.4
          ports:
          - containerPort: 27017
            protocol: TCP 
          volumeMounts:
            - name: jd-nfs-pvc-unifi
              mountPath: /docker-entrypoint-initdb.d/
              subPath: unifi-appliance-mongo
            - name: jd-nfs-pvc-unifi 
              mountPath: /data/db
              subPath: unifi-appliance-mongo-db
      volumes:
        - name: jd-nfs-pvc-unifi
          persistentVolumeClaim:
            claimName: jd-nfs-pvc-unifi
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-bgp
  namespace: unifi
spec:
  ports:
    - name: "8080"
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: "8443"
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: "8843"
      protocol: TCP
      port: 8843
      targetPort: 8843
    - name: "8880"
      protocol: TCP
      port: 8880
      targetPort: 8880
    - name: "6789"
      protocol: TCP
      port: 6789
      targetPort: 6789
    - name: "3478"
      protocol: UDP
      port: 3478
      targetPort: 3478
  selector:
    name: unifi
  type: ClusterIP 
