apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zabbix-agent
  labels:
    app: zabbix
    tier: agent
  namespace: zabbix
  annotations:
    argocd-image-updater.argoproj.io/image-list: zabbix-agent
    argocd-image-updater.argoproj.io/zabbix-agent.update-strategy: latest
spec:
  selector:
   matchLabels:
    app: zabbix
    name: zabbix-agent
  updateStrategy:
   type: RollingUpdate
   rollingUpdate:
    maxUnavailable: 1
  template:
    metadata:
      labels:
        name: zabbix-agent
        app: zabbix
    spec:
      hostNetwork: true
      hostIPC: true
      hostPID: true
      automountServiceAccountToken: true
      serviceAccountName: zabbix-agent
      containers:
        - name: zabbix-agent
          image: zabbix/zabbix-agent:alpine-7.0-latest
          imagePullPolicy: Always
          resources:
           limits:
            cpu: 100m
            memory: 54Mi
           requests:
            cpu: 100m
            memory: 54Mi
          ports:
          - containerPort: 10050
            name: zabbix-agent
          env:
            - name: ZBX_DEBUGLEVEL
              value: "3"
            - name: ZBX_DENYKEY
              value: "system.run[*]"
            - name: ZBX_ALLOWKEY
              value: ""
            - name: ZBX_LOGREMOTECOMMANDS
              value: "1"
            - name: ZBX_SERVER_HOST
              value: "zabbix-server"
            - name: ZBX_PASSIVE_ALLOW
              value: "true"
            - name: ZBX_PASSIVESERVERS
              value: ""
            - name: ZBX_ACTIVE_ALLOW
              value: "true"
            - name: ZBX_ACTIVESERVERS
              value: ""
            - name: ZBX_STARTAGENTS
              value: ""
            - name: ZBX_HOSTNAME
              valueFrom:
               fieldRef:
                 fieldPath: spec.nodeName
            - name: ZBX_HOSTNAMEITEM
              value: ""
            - name: ZBX_METADATA
              value: ""
            - name: ZBX_METADATAITEM
              value: ""
            - name: ZBX_TIMEOUT
              value: ""
            - name: ZBX_BUFFERSEND
              value: ""
            - name: ZBX_BUFFERSIZE
              value: ""
            - name: ZBX_MAXLINESPERSECOND
              value: ""
            - name: ZBX_UNSAFEUSERPARAMETERS
              value: "0"
            - name: ZBX_LOADMODULE
              value: ""
            - name: ZBX_HOSTINTERFACE
              value: ""
            - name: ZBX_HOSTINTERFACEITEM
              value: ""
            - name: ZBX_REFRESHACTIVECHECKS
              value: ""
            - name: DEBUG_MODE
              value: "3"
            - name: ZBX_TLSCONNECT
              value: ""
            - name: ZBX_TLSACCEPT
              value: ""
            - name: ZBX_TLSCAFILE
              value: ""
            - name: ZBX_TLSCRLFILE
              value: ""
            - name: ZBX_TLSSERVERCERTISSUER
              value: ""
            - name: ZBX_TLSSERVERCERTSUBJECT
              value: ""
            - name: ZBX_TLSCERTFILE
              value: ""
            - name: ZBX_TLSKEYFILE
              value: ""
            - name: ZBX_TLSPSKIDENTITY
              value: ""
            - name: ZBX_TLSPSKFILE
              value: ""
            - name: ZBX_TLSCIPHERALL
              value: ""
            - name: ZBX_TLSCIPHERALL13
              value: ""
            - name: ZBX_TLSCIPHERCERT
              value: ""
            - name: ZBX_TLSCIPHERCERT13
              value: ""
            - name: ZBX_TLSCIPHERPSK
              value: ""
            - name: ZBX_TLSCIPHERPSK13
              value: ""
          securityContext:
            capabilities: {}
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          volumeMounts:
            - name: dev-volume
              mountPath: /node/dev
            - name: procfs-volume
              readOnly: true
              mountPath: /node/proc
            - name: boot-volume
              readOnly: true
              mountPath: /node/boot
            - name: run-volume
              mountPath: /node/run
            - name: var-run-volume
              mountPath: /node/var/run
      volumes:
        - name: dev-volume
          hostPath:
            path: /dev
            type: ''
        - name: procfs-volume
          hostPath:
            path: /proc
            type: ''
        - name: boot-volume
          hostPath:
            path: /boot
            type: ''
        - name: run-volume
          hostPath:
            path: /run
            type: ''
        - name: var-run-volume
          hostPath:
            path: /var/run
            type: ''