apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: tigera-operator
  source:
    chart: tigera-operator
    repoURL: https://docs.tigera.io/calico/charts 
    targetRevision: v3.29.1
    helm:
      releaseName: calico
      valuesObject:
        calicoNetwork:
          containerIPForwarding: Enabled
          bgp: Enabled
          ipPools:
          - allowedUses:
                - Workload
                - Tunnel
            name: default-ipv4-ippool
            disableBGPExport: false
            blockSize: 26
            cidr: 10.244.0.0/16
            encapsulation: IPIPCrossSubnet
            natOutgoing: Enabled
            nodeSelector: all()
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

