apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: quay.io/jetstack/charts
    chart: cert-manager
    # Pick a recent stable version; update as needed (chart/app versions match).
    # Examples: v1.15.3, v1.16.1, etc.
    targetRevision: v1.18.2
    helm:
      values: |
        crds:
          enabled: true
        # (Optional) set leader election namespace explicitly
        global:
          leaderElection:
            namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true     
