apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-smb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts"
    chart: csi-driver-smb
    targetRevision: 1.20.3
    helm:
      releaseName: csi-driver-smb
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
