apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://charts.external-secrets.io'
      targetRevision: v1.3.1
      chart: external-secrets
      helm:
        values: |
          installCRDs: true

          replicaCount: 1

          # Mount NFS volume to ESO pods
          extraVolumes:
          - name: secrets-store
            persistentVolumeClaim:
              claimName: eso-secrets-pvc

          extraVolumeMounts:
          - name: secrets-store
            mountPath: /secrets
            readOnly: true
    - repoURL: "https://github.com/Jayden-Lind/LINDS-Kubernetes"
      targetRevision: HEAD
      path: external-secrets/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
