apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: factorio
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: factorio=factoriotools/factorio:stable
    argocd-image-updater.argoproj.io/factorio.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Jayden-Lind/LINDS-Kubernetes"
    targetRevision: HEAD
    path: "factorio"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: factorio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - Validate=false
      - ServerSideApply=true
      - CreateNamespace=true