apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-pre-requisites
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Jayden-Lind/LINDS-Kubernetes'
    targetRevision: HEAD
    path: "github-runner"
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
