apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
  namespace: argocd          
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default 
  source:
    repoURL: https://kubereboot.github.io/charts          
    chart: kured
    targetRevision: "5.10.0" 
    helm:
      releaseName: kured
      values: |
        namespace: kube-system

        configuration:
          period: 1h0m0s
          timeZone: "Etc/UTC"
          lockTtl: 30m
          drainTimeout: 10m
          forceReboot: true
          annotateNodes: true
          skipWaitForDeleteTimeout: 120
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:                 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   

