apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mumble
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: mumble
  source:
    repoURL: https://syntax3rror404.github.io/helm-charts/charts
    chart: mumble
    targetRevision: 1.0.2
    helm:
      values: |
        service:
          type: LoadBalancer
        persistence:
          storageClass: nfs-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

