apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-problem-detector
  namespace: argocd
spec:
  project: default
  source:
    chart: node-problem-detector
    repoURL: ghcr.io/deliveryhero/helm-charts
    targetRevision: 2.3.22
    helm:
      releaseName: node-problem-detector
      values: |
        namespace: kube-system
        metrics:
          enabled: true
          serviceMonitor.enabled: true
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

