apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-jd
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: plex-jd
  sources:
    - repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
      chart: plex-media-server
      targetRevision: 1.4.0
      helm:
        values: |
          image:
            tag: latest
          nameOverride: plex-jd
          ingress:
            enabled: true
            ingressClassName: nginx
            url: plex.linds.com.au
            tls:
              - hosts:
                - plex.linds.com.au
            annotations:
              cert-manager.io/cluster-issuer: linds-ca
          pms:
            storageClassName: nfs-csi
            configStorage: 50Gi
          service:
            type: LoadBalancer
            annotations: 
              projectcalico.org/ipv4pools: '["lb-172-16-1"]'
              projectcalico.org/loadBalancerIPs: '["172.16.1.50"]'
          nodeSelector:
            datacenter: jd
          extraVolumeMounts:
            - name: nas
              mountPath: /data/media
            - name: holiday
              mountPath: /data/holiday
          extraVolumes:
            - name: holiday
              persistentVolumeClaim:
                claimName: holiday-videos-pvc
            - name: nas
              persistentVolumeClaim:
                claimName: jd-torrent-pvc
    - repoURL: "https://github.com/Jayden-Lind/LINDS-Kubernetes"
      targetRevision: HEAD
      path: plex-jd/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

