apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql-linds
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: 0.26.0
    - repoURL: https://github.com/Jayden-Lind/LINDS-Kubernetes
      targetRevision: master
      path: postgresql
    - repoURL: https://cloudnative-pg.github.io/grafana-dashboards
      chart: cluster
      targetRevision: v0.0.5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - Validate=false
      - ServerSideApply=true
      - CreateNamespace=true

