---
apiVersion: batch/v1
kind: Job
metadata:
  name: label-linds-kube-nodes
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: pre-sync-hook-sa
      containers:
        - name: label-nodes
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              for node in $(kubectl get nodes --no-headers -o custom-columns=":metadata.name" | grep "^linds-kube-"); do
                kubectl label nodes $node datacenter=linds --overwrite;
              done
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - jd-kube-01
  backoffLimit: 4
