---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-secret
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/hook-failed: Skip
spec:
  template:
    spec:
      serviceAccountName: pre-sync-hook-sa
      containers:
        - name: create-secret
          image: bitnami/kubectl:latest
          command:
            [
              "sh",
              "-c",
              "(kubectl apply -f /root/k8s/base/linds-secret.yml || true)"
            ]
          volumeMounts:
            - name: secret-file
              mountPath: /root/k8s
              readOnly: true
          securityContext:
            privileged: true
      restartPolicy: Never
      volumes:
        - name: secret-file
          hostPath:
            path: /root/k8s
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - jd-kube-01
  backoffLimit: 0
