---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-secret
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: create-secret
        image: bitnami/kubectl:latest
        command: ["sh", "-c", "kubectl apply -f /root/k8s/secret.yaml"]
        volumeMounts:
        - name: secret-file
          mountPath: /root/k8s
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: secret-file
        hostPath:
          path: /root/k8s
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - jd-kube-01
  backoffLimit: 4