apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: satisfactory-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: satisfactory=wolveix/satisfactory-server:latest
    argocd-image-updater.argoproj.io/satisfactory.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Jayden-Lind/LINDS-Kubernetes"
    targetRevision: HEAD
    path: "satisfactory"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: satisfactory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true