apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfactory
spec:
  selector:
    matchLabels:
      app: satisfactory
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      nodeSelector:
        datacenter: jd
      containers:
        - name: satisfactory
          image: wolveix/satisfactory-server:dev
          ports:
            - containerPort: 7777
              protocol: UDP
            - containerPort: 7777
              protocol: TCP
          env:
            - name: NETWORKQUALITY
              value: "5"
            - name: TZ
              value: Australia/Melbourne
            - name: SERVERIP
              value: "0.0.0.0"
          volumeMounts:
            - name: jd-nfs-pvc-satisfactory
              mountPath: config/
              subPath: satisfactory
      volumes:
        - name: jd-nfs-pvc-satisfactory
          persistentVolumeClaim:
            claimName: jd-nfs-pvc-satisfactory
