apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jd-nfs-pvc-satisfactory
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
