apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  namespace: argocd
spec:
  selector:
    app: satisfactory
  ports:
    - port: 7777
      name: satisfactory-udp-game
      targetPort: 7777
      protocol: UDP
    - port: 7777
      name: satisfactory-tcp-game
      targetPort: 7777
      protocol: TCP
  type: LoadBalancer
  externalIPs:
    - 172.16.1.1
