---
apiVersion: v1
kind: Namespace
metadata:
  name: palworld
  labels:
    name: home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jd-nfs-pvc-palworld
  namespace: palworld
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: palworld
  namespace: palworld
spec:
  selector:
    matchLabels:
      app: palworld
  template:
    metadata:
      labels:
        app: palworld
    spec:
      nodeSelector:
        datacenter: jd
      containers:
        - name: palworld
          image: thijsvanloef/palworld-server-docker
          ports:
            - containerPort: 8211
              protocol: UDP
            - containerPort: 27016
              protocol: UDP
          env:
            - name: PORT
              value: "8211"
            - name: PLAYERS
              value: "16"
            - name: MULTITHREADING
              value: "true"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: jd-nfs-pvc-palworld
              mountPath: palworld/
              subPath: palworld
      volumes:
        - name: jd-nfs-pvc-palworld
          persistentVolumeClaim:
            claimName: jd-nfs-pvc-palworld
---
apiVersion: v1
kind: Service
metadata:
  name: palworld
  namespace: palworld
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  selector:
    app: palworld
  ports:
    - port: 8211
      name: palworld-udp-game
      targetPort: 8211
      protocol: UDP
    - port: 27016
      name: palworld-udp-game-remote
      targetPort: 27016
      protocol: UDP
    - port: 25575
      name: palworld-udp-game-admin
      targetPort: 25575
      protocol: UDP
  type: LoadBalancer
  externalIPs:
    - 172.16.1.5
