apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: calico-felix
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - calico-system
  selector:
    matchLabels:
      k8s-app: calico-node
  podMetricsEndpoints:
    - interval: 30s
      scheme: http
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_ip]
          targetLabel: __address__
          replacement: $1:9092
