apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zabbix-agent
  namespace: zabbix
rules:
- verbs:
  - use
  apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
  - hostaccess
  - hostnetwork
