apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  template:
    spec:
      containers:
      - name: argocd-image-updater
        args:
          - run
          - --loglevel=debug
          - --interval=60m