apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: external-secrets-system
spec:
  provider:
    vault:
      server: "https://vault.linds.com.au"
      path: "linds-keyvault"
      version: "v2"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtVENDQW9HZ0F3SUJBZ0lRZWJMaVB5R3VGWUpKZG1KUTk0eWJrekFOQmdrcWhraUc5dzBCQVFzRkFEQlQKTVJJd0VBWUtDWkltaVpQeUxHUUJHUllDWVhVeEV6QVJCZ29Ka2lhSmsvSXNaQUVaRmdOamIyMHhGVEFUQmdvSgpraWFKay9Jc1pBRVpGZ1ZzYVc1a2N6RVJNQThHQTFVRUF4TUliR2x1WkhNdFEwRXdIaGNOTVRreE1qQXhNRE16Ck16UTNXaGNOTWpreE1qQXhNRE0wTXpRM1dqQlRNUkl3RUFZS0NaSW1pWlB5TEdRQkdSWUNZWFV4RXpBUkJnb0oKa2lhSmsvSXNaQUVaRmdOamIyMHhGVEFUQmdvSmtpYUprL0lzWkFFWkZnVnNhVzVrY3pFUk1BOEdBMVVFQXhNSQpiR2x1WkhNdFEwRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEVnYzOFhJZG1vClNjRmk2RGhTeTB1WEVsa1ZiU0FPSlQxNHdLYkUzWnhuV1VLUkx6SDI1aERiTVFsVjJ1UStHNTlXbnJlSWh4cE4KeFNPcDlSWHJKbjJJQTJ0TlZPV1RSQkZnM0NTc1hSbC9FUWYxZWxieDdqNEFlRXpDNE1kQjNsUEJGVjgxNzVYbQpjdWVDY21xbEkzdVp1ZGJCYklLaUk0SEs5UkpxV2pPQ0RHODI3WUg3WitNZC9zYlcxUzUzV1RDWmhUdXgwVFVVClJNbysxMTRpZDBKcW5RMGNLUVJPRG1DdWltSlZZRW1Zam9GL2tBUmYyK2p0Qldxb1JSdXlIc3dCRTVENkw0bTQKczlsblg5bTBmTmJYakMwMElGbFJkcklET2FtZW81Vkx4a0ViMHlJR0xwTWxhK254Um1KZ2RURHFXaW56bU13NQp2VUpUS2QzU25oUmRBZ01CQUFHamFUQm5NQk1HQ1NzR0FRUUJnamNVQWdRR0hnUUFRd0JCTUE0R0ExVWREd0VCCi93UUVBd0lCaGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSajI4SXBiWDdUTFVUNE1LdFcKcStwaHRrZmI3REFRQmdrckJnRUVBWUkzRlFFRUF3SUJBREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBdHRzMwpzUWpkYVFlbk9VWDBCcVcwNkJBRWRQSmM2ZDFLNS83OWNxZlp4MTVqQnh0am9EVVE2MGcwTkI1dWorN2FaeWdTCmJsT2FtbWlTeVpCMUhGL1Yzc1lwRmdvUGNwZ0hnMGRReVI3a2EvZkpJQ0s4aGo0KzVkZVhROWxiYXNkcE5RdUcKalFXQzJnWGQveTB3MG1SY2JaYmNCMnRUTHBEOE0ydHNpZ1p4UWpJSUliV2htZjRSRFlJRzhIS2hGUlJmTVRZaAoxaE1PVFpWUTYyNk9nOHhvemZtdTZVTkJDM1ZmcjM3OUxSMDBJTSswWWhQeTJRTHVWUVA0U09zNnJXbGxhRGVXCmFxTVo0Y2F3elQxVlo0SHZWMGdhUmwvd3Rma2RZVnUwUXV6d1llMG01eEF5V2RHdWlkcmE4Y29zdlVnREdaQmIKWml0ZGdjK0M5M2ZwY1Q4VXBBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: default
          key: token
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eso-secrets-pvc
  namespace: external-secrets-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi