apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: argocd-admin
spec:
  externalSecretName: argocd-secret
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: argocd
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: argocd-secret
      creationPolicy: Orphan
      deletionPolicy: Retain
    data:
      - secretKey: admin.password
        remoteRef:
          key: linds-keyvault/argocd-secret
          property: admin.password
      - secretKey: admin.passwordMtime
        remoteRef:
          key: linds-keyvault/argocd-secret
          property: admin.passwordMtime
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: linds-certificate-secret
spec:
  externalSecretName: linds-certificate-secret
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: default
    - matchLabels:
        kubernetes.io/metadata.name: nginx-ingress
    - matchLabels:
        kubernetes.io/metadata.name: argocd
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: linds-certificate-secret
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/linds-certificate-secret
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: linds-smb-secret
spec:
  externalSecretName: linds-smb-secret
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: default
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: linds-smb-secret
      creationPolicy: Orphan
      deletionPolicy: Retain
      template:
        type: smb.csi.k8s.io
    dataFrom:
      - extract:
          key: linds-keyvault/linds-smb-secret
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: postgres-secret-lindrea
spec:
  externalSecretName: postgres-secret-lindrea
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: default
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: postgres-secret-lindrea
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/postgres-secret-lindrea
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: registry-cert
spec:
  externalSecretName: registry-cert
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: container-registry
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: registry-cert
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/registry-cert
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: postgres-linds-postgresql-credentials
spec:
  externalSecretName: postgres.linds-postgresql.credentials.postgresql.acid.zalan.do
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: zabbix
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: postgres.linds-postgresql.credentials.postgresql.acid.zalan.do
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/postgres.linds-postgresql.credentials.postgresql.acid.zalan.do
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: pre-defined-secret
spec:
  externalSecretName: pre-defined-secret
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: arc-runners
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: pre-defined-secret
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/pre-defined-secret
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: ghcr-pull-secret
spec:
  externalSecretName: ghcr-pull-secret
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: default
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: ghcr-pull-secret
      creationPolicy: Orphan
      deletionPolicy: Retain
      template:
        type: kubernetes.io/dockerconfigjson
    dataFrom:
      - extract:
          key: linds-keyvault/ghcr-pull-secret
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: catcrawl-env-secret
spec:
  externalSecretName: catcrawl-env-secret
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: default
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: catcrawl-env-secret
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/catcrawl-env-secret
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: catcrawl-coles-env-secret
spec:
  externalSecretName: catcrawl-coles-env-secret
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: default
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: catcrawl-coles-env-secret
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/catcrawl-coles-env-secret
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: postgres-user
spec:
  externalSecretName: postgres-user
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: postgresql-linds
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: postgres-user
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/postgres-user
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cnpg-s3-creds
spec:
  externalSecretName: cnpg-s3-creds
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: postgresql-linds
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: cnpg-s3-creds
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/cnpg-s3-creds
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: catcrawl-auth
spec:
  externalSecretName: catcrawl-auth
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: postgresql-linds
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: catcrawl-auth
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/catcrawl-auth
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: smb-immich-creds
spec:
  externalSecretName: smb-immich-creds
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: immich
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: smb-immich-creds
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/smb-immich-creds
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: immich-auth
spec:
  externalSecretName: immich-auth
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: postgresql-linds
    - matchLabels:
        kubernetes.io/metadata.name: immich
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: immich-auth
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/immich-auth
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: linds-ca-keypair
spec:
  externalSecretName: linds-ca-keypair
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: cert-manager
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: linds-ca-keypair
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/linds-ca-keypair
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: vault-token
spec:
  externalSecretName: vault-token
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: default
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: vault-token
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/vault-token
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: grafana-credentials
spec:
  externalSecretName: grafana-credentials
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: monitoring
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: grafana-credentials
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/grafana-credentials
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: loki-access-creds
spec:
  externalSecretName: loki-access-creds
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: monitoring
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: loki-access-creds
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/loki-access-creds
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: smb-plex-secret
spec:
  externalSecretName: smb-plex-secret
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: plex-jd
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: OnChange
    target:
      name: smb-plex-secret
      creationPolicy: Orphan
      deletionPolicy: Retain
    dataFrom:
      - extract:
          key: linds-keyvault/smb-plex-secret