apiVersion: v1
kind: PersistentVolume
metadata:
  name: jd-nfs-truenas
  labels:
    storage.k8s.io/name: nfs
    storage.k8s.io/part-of: kubernetes-complete-reference
    volume.beta.kubernetes.io/mount-options: soft
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: "manual"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    server: jd-truenas-01.linds.com.au
    path: /mnt/NAS
    readOnly: false