apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
spec:
  template:
    spec:
      containers:
        - name: main
          volumeMounts:
            - mountPath: /usr/src/app/library
              name: library
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: immich-library-pvc