apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-immich
  namespace: immich
provisioner: smb.csi.k8s.io
parameters:
  source: "//jd-dc-01.linds.com.au/nas/photos"
  csi.storage.k8s.io/provisioner-secret-name: smb-immich-creds
  csi.storage.k8s.io/provisioner-secret-namespace: immich
  csi.storage.k8s.io/node-stage-secret-name: smb-immich-creds
  csi.storage.k8s.io/node-stage-secret-namespace: immich
mountOptions:
  - soft
  - dir_mode=0777
  - file_mode=0777
  - domain=linds.com.au
  - vers=3.1.1
reclaimPolicy: Retain
allowVolumeExpansion: false
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: smb-immich
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-immich-photos
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=3.0
    - file_mode=0777
    - dir_mode=0777
    - nounix
  csi:
    driver: smb.csi.k8s.io
    # unique id for this share in the cluster
    volumeHandle: pv-immich-photos-handle
    readOnly: false
    # volumeAttributes are driver-specific. For the common smb.csi.k8s.io driver use "source"
    volumeAttributes:
      source: "//jd-dc-01.linds.com.au/nas/photos"
    # These must point to a Secret that contains the SMB user/password
    nodePublishSecretRef:
      name: smb-immich-creds
      namespace: immich
    nodeStageSecretRef:
      name: smb-immich-creds
      namespace: immich