apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft 
  annotations:
    argocd-image-updater.argoproj.io/image-list: minecraft
    argocd-image-updater.argoproj.io/minecraft.update-strategy: digest
