apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  namespace: arr
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: zfs-iscsi
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: arr
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: zfs-iscsi
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: arr
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: zfs-iscsi
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: arr
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: zfs-iscsi
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maintainerr-config
  namespace: arr
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: zfs-iscsi
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: linds-nfs-nas
  labels:
    storage.k8s.io/name: nfs
    storage.k8s.io/part-of: kubernetes-complete-reference
    volume.beta.kubernetes.io/mount-options: soft
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 1Ti
  storageClassName: "manual"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    server: linds-truenas-01.linds.com.au
    path: /mnt/ZFS_NAS
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linds-nfs-nas-pvc
  namespace: arr
spec:
  storageClassName: "manual"
  volumeName: linds-nfs-nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: arr
spec:
  selector:
    matchLabels:
      app: jackett
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jackett
    spec:
      terminationGracePeriodSeconds: 120
      nodeSelector:
        datacenter: linds
      containers:
        - name: jackett
          image: linuxserver/jackett:latest
          volumeMounts:
            - mountPath: /config
              name: arr-config
          ports:
            - containerPort: 9117
      restartPolicy: Always
      volumes:
        - name: arr-config
          persistentVolumeClaim:
            claimName: jackett-config
---
apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: arr
spec:
  ports:
    - port: 9117
      targetPort: 9117
      protocol: TCP
      name: http
  selector:
    app: jackett
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett
  namespace: arr
  annotations:
    cert-manager.io/cluster-issuer: linds-ca
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: jackett.linds.com.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jackett
                port:
                  number: 9117
  tls:
    - hosts:
        - jackett.linds.com.au
      secretName: jackett-linds-com-au-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: arr
spec:
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      terminationGracePeriodSeconds: 120
      nodeSelector:
        datacenter: linds
      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          env:
            - name: GUID
              value: "0"
            - name: PUID
              value: "1000"
          volumeMounts:
            - mountPath: /config
              name: arr-config
            - name: linds-nfs-nas
              mountPath: /mnt/nas/torrent
              subPath: torrent
            - name: linds-nfs-nas
              mountPath: /mnt/nas/Movies
              subPath: Movies
          ports:
            - containerPort: 7878
      restartPolicy: Always
      volumes:
        - name: arr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: linds-nfs-nas
          persistentVolumeClaim:
            claimName: linds-nfs-nas-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: arr
spec:
  ports:
    - port: 7878
      targetPort: 7878
      protocol: TCP
      name: http
  selector:
    app: radarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: arr
  annotations:
    cert-manager.io/cluster-issuer: linds-ca
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.org/websocket-services: "radarr"
    linds.com.au/mtls-mirror: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: radarr.linds.com.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  number: 7878
  tls:
    - hosts:
        - radarr.linds.com.au
      secretName: radarr-linds-com-au-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: arr
spec:
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      terminationGracePeriodSeconds: 120
      nodeSelector:
        datacenter: linds
      containers:
        - name: sonarr
          image: linuxserver/sonarr:latest
          env:
            - name: GUID
              value: "0"
            - name: PUID
              value: "1000"
            - name: SONARR_BRANCH
              value: main
          volumeMounts:
            - mountPath: /config
              name: arr-config
            - name: linds-nfs-nas
              mountPath: /mnt/torrent
              subPath: torrent
            - name: linds-nfs-nas
              mountPath: /mnt/TVShows
              subPath: TVShows
            - name: linds-nfs-nas
              mountPath: /mnt/Movies
              subPath: Movies
          ports:
            - containerPort: 8989
      restartPolicy: Always
      volumes:
        - name: arr-config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: linds-nfs-nas
          persistentVolumeClaim:
            claimName: linds-nfs-nas-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: arr
spec:
  ports:
    - port: 8989
      targetPort: 8989
      protocol: TCP
      name: http
  selector:
    app: sonarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  namespace: arr
  annotations:
    cert-manager.io/cluster-issuer: linds-ca
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.org/websocket-services: "sonarr"
    linds.com.au/mtls-mirror: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: sonarr.linds.com.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989
  tls:
    - hosts:
        - sonarr.linds.com.au
      secretName: sonarr-linds-com-au-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: arr
spec:
  selector:
    matchLabels:
      app: bazarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      terminationGracePeriodSeconds: 120
      nodeSelector:
        datacenter: linds
      containers:
        - name: bazarr
          image: linuxserver/bazarr:latest
          env:
            - name: GUID
              value: "0"
            - name: PUID
              value: "1000"
          volumeMounts:
            - mountPath: /config
              name: arr-config
            - name: linds-nfs-nas
              mountPath: /mnt/TVShows
              subPath: TVShows
            - name: linds-nfs-nas
              mountPath: /mnt/Movies
              subPath: Movies
            - name: linds-nfs-nas
              mountPath: /mnt/torrent
              subPath: torrent
          ports:
            - containerPort: 6767
      restartPolicy: Always
      volumes:
        - name: arr-config
          persistentVolumeClaim:
            claimName: bazarr-config
        - name: linds-nfs-nas
          persistentVolumeClaim:
            claimName: linds-nfs-nas-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: arr
spec:
  ports:
    - port: 6767
      targetPort: 6767
      protocol: TCP
      name: http
  selector:
    app: bazarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr
  namespace: arr
  annotations:
    cert-manager.io/cluster-issuer: linds-ca
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.org/websocket-services: "bazarr"
spec:
  ingressClassName: nginx
  rules:
    - host: bazarr.linds.com.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bazarr
                port:
                  number: 6767
  tls:
    - hosts:
        - bazarr.linds.com.au
      secretName: bazarr-linds-com-au-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintainerr
  namespace: arr
spec:
  selector:
    matchLabels:
      app: maintainerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: maintainerr
    spec:
      terminationGracePeriodSeconds: 120
      nodeSelector:
        datacenter: linds
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: maintainerr
          image: ghcr.io/maintainerr/maintainerr:latest
          volumeMounts:
            - mountPath: /opt/data
              name: arr-config
          ports:
            - containerPort: 6246
      restartPolicy: Always
      volumes:
        - name: arr-config
          persistentVolumeClaim:
            claimName: maintainerr-config
---
apiVersion: v1
kind: Service
metadata:
  name: maintainerr
  namespace: arr
spec:
  ports:
    - port: 6246
      targetPort: 6246
      protocol: TCP
      name: http
  selector:
    app: maintainerr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maintainerr
  namespace: arr
  annotations:
    cert-manager.io/cluster-issuer: linds-ca
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.org/websocket-services: "maintainerr"
spec:
  ingressClassName: nginx
  rules:
    - host: maintainerr.linds.com.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: maintainerr
                port:
                  number: 6246
  tls:
    - hosts:
        - maintainerr.linds.com.au
      secretName: maintainerr-linds-com-au-tls
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: arr
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: zfs-iscsi
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: arr
spec:
  selector:
    matchLabels:
      app: tautulli
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      terminationGracePeriodSeconds: 120
      nodeSelector:
        datacenter: linds
      containers:
        - name: tautulli
          image: linuxserver/tautulli:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "0"
          volumeMounts:
            - mountPath: /config
              name: tautulli-config
          ports:
            - containerPort: 8181
      restartPolicy: Always
      volumes:
        - name: tautulli-config
          persistentVolumeClaim:
            claimName: tautulli-config
---
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: arr
spec:
  ports:
    - port: 8181
      targetPort: 8181
      protocol: TCP
      name: http
  selector:
    app: tautulli
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli
  namespace: arr
  annotations:
    cert-manager.io/cluster-issuer: linds-ca
    nginx.org/websocket-services: "tautulli"
spec:
  ingressClassName: nginx
  rules:
    - host: tautulli.linds.com.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tautulli
                port:
                  number: 8181
  tls:
    - hosts:
        - tautulli.linds.com.au
      secretName: tautulli-linds-com-au-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: arr
spec:
  selector:
    matchLabels:
      app: flaresolverr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      terminationGracePeriodSeconds: 120
      nodeSelector:
        datacenter: linds
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          env:
            - name: LOG_LEVEL
              value: info
            - name: TZ
              value: Australia/Sydney
          ports:
            - containerPort: 8191
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: arr
spec:
  ports:
    - port: 8191
      targetPort: 8191
      protocol: TCP
      name: http
  selector:
    app: flaresolverr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flaresolverr
  namespace: arr
  annotations:
    cert-manager.io/cluster-issuer: linds-ca
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: flaresolverr.linds.com.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flaresolverr
                port:
                  number: 8191
  tls:
    - hosts:
        - flaresolverr.linds.com.au
      secretName: flaresolverr-linds-com-au-tls
