apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-iscsi-arr-suite
spec:
  capacity:
    storage: 10Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  iscsi:
    targetPortal: "10.0.53.20:3260"
    portals: []
    iqn: "iqn.2005-10.org.truenas:arr-suite"
    lun: 0
    fsType: ext4
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linds-arr-config
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: pv-iscsi-arr-suite
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linds-nfs-nas-pvc
  namespace: default
spec:
  storageClassName: "manual"
  volumeName: linds-nfs-nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linds-docker
  namespace: default
spec:
  selector:
    matchLabels:
      app: v1
      name: linds-docker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: v1
        name: linds-docker
      annotations:
        diun.enable: "true"
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: jacket
          image: linuxserver/jackett:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /config
              name: linds-nfs-pvc
              subPath: jackett
          ports:
            - containerPort: 9117
        - name: radarr
          env:
            - name: GUID
              value: "0"
            - name: PUID
              value: "1000"
          image: linuxserver/radarr:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /config
              name: linds-nfs-pvc
              subPath: radarr
            - name: linds-nfs-nas
              mountPath: /mnt/nas/torrent
              subPath: torrent
            - name: linds-nfs-nas
              mountPath: "/mnt/nas/Movies"
              subPath: "Movies"
          ports:
            - containerPort: 7878
        - name: sonarr
          env:
            - name: GUID
              value: "0"
            - name: PUID
              value: "1000"
            - name: SONARR_BRANCH
              value: main
          image: linuxserver/sonarr:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /config
              name: linds-nfs-pvc
              subPath: sonarr
            - name: linds-nfs-nas
              mountPath: /mnt/torrent
              subPath: torrent
            - name: linds-nfs-nas
              mountPath: "/mnt/TV Shows"
              subPath: "TV Shows"
            - name: linds-nfs-nas
              mountPath: "/mnt/Movies"
              subPath: "Movies"
          ports:
            - containerPort: 8989
      restartPolicy: Always
      volumes:
        - name: linds-nfs-pvc
          persistentVolumeClaim:
            claimName: linds-arr-config
        - name: linds-nfs-nas
          persistentVolumeClaim:
            claimName: linds-nfs-nas-pvc
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: linds-docker
  labels:
    app: linds-docker
spec:
  ports:
    - port: 8989
      targetPort: 8989
      protocol: TCP
      name: sonarr-service
    - port: 9117
      targetPort: 9117
      protocol: TCP
      name: jackett-service
    - port: 7878
      targetPort: 7878
      protocol: TCP
      name: radarr-service
  selector:
    name: linds-docker
