apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-web
  labels:
    app: zabbix
    tier: zabbix-web
  namespace: zabbix
  annotations:
    argocd-image-updater.argoproj.io/image-list: zabbix-web-service-nginx
    argocd-image-updater.argoproj.io/zabbix-web-service-nginx.update-strategy: digest
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: zabbix-web
        app: zabbix
    spec:
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: web-http
          - containerPort: 8443
            name: web-https
          resources:
           limits:
            cpu: 200m
            memory: 400Mi
           requests:
            cpu: 200m
            memory: 400Mi
          env:
          - name: ZBX_SERVER_NAME
            value: "LINDS-Zabbix"
          - name: PHP_TZ
            value: "Australia/Melbourne"
          - name: DB_SERVER_HOST
            value: linds-postgresql.postgresql-linds.svc.cluster.local
          - name: DB_SERVER_PORT
            value: "5432"
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres.linds-postgresql.credentials.postgresql.acid.zalan.do
                key: password
          - name: POSTGRES_DB
            value: zabbix
          - name: ZBX_DB_VERIFY_HOST
            value: "false"
          - name: ZBX_DB_CIPHER_LIST
            value: ""
          - name: ZBX_SSO_SETTINGS
            value: "[]"
          - name: ENABLE_WEB_ACCESS_LOG
            value: "true"
          - name: DEBUG_MODE
            value: "false"
