apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: linds-ca
    nginx.org/ssl-redirect: "true"
    nginx.org/grpc-services: "argocd-server"
    nginx.org/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: argocd.linds.com.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
  tls:
    - hosts:
        - argocd.linds.com.au
      secretName: argocd-linds-com-au-tls
