apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stirling-pdf-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: linds-ca
spec:
  ingressClassName: nginx
  rules:
    - host: pdf.linds.com.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stirling-pdf-service
                port:
                  number: 8080
  tls:
    - hosts:
        - pdf.linds.com.au
      secretName: pdf-linds-tls
