---
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default 
spec:
  nodeToNodeMeshEnabled: true
  logSeverityScreen: Info
  serviceClusterIPs:
    - cidr: 10.96.0.0/12 
  serviceExternalIPs:
    - cidr: 172.16.1.0/24
  listenPort: 179
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: jd-vyos-01-peer
spec:
  peerIP: 10.0.53.1
  asNumber: 64550
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: linds-vyos-01-peer
spec:
  peerIP: 10.3.1.1
  asNumber: 64551