apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: default
spec:
  bpfExternalServiceMode: DSR   
  bpfConnectTimeLoadBalancing: Enabled
  bpfEnabled: true
  bpfEnforceRPF: Disabled
  bpfHostNetworkedNATWithoutCTLB: Disabled

