apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: factorio
  namespace: argocd
spec:
  namespace: argocd
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: factorio
      images:
        - alias: factorio
          imageName: factoriotools/factorio:stable
          commonUpdateSettings:
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: factoriotools/factorio
