apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: minecraft
  namespace: argocd
spec:
  namespace: argocd
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: minecraft
      images:
        - alias: minecraft
          imageName: itzg/minecraft-server:latest
          commonUpdateSettings:
            updateStrategy: digest
          manifestTargets:
            kustomize:
              name: itzg/minecraft-server
