apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: plex-jd
  namespace: argocd
spec:
  namespace: argocd
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: plex-jd
      images:
        - alias: plex
          imageName: index.docker.io/plexinc/pms-docker:latest
          commonUpdateSettings:
            updateStrategy: digest
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
