apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: satisfactory
  namespace: argocd
spec:
  namespace: argocd
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: satisfactory-app
      images:
        - alias: satisfactory
          imageName: wolveix/satisfactory-server:latest
          commonUpdateSettings:
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: wolveix/satisfactory-server
