apiVersion: apps/v1
kind: Deployment
metadata:
  name: catcrawl-coles-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catcrawl-coles-api
  template:
    metadata:
      labels:
        app: catcrawl-coles-api
    spec:
      containers:
      - name: catcrawl-coles-api
        image: ghcr.io/jayden-lind/cat-crawl-coles-api:latest
        imagePullPolicy: Always
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: catcrawl-coles-env-secret
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: catcrawl-coles-env-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: catcrawl-coles-env-secret
                key: DB_PASSWORD
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: catcrawl-coles-env-secret
                key: DB_PORT
        ports:
          - containerPort: 3000
            protocol: TCP
      imagePullSecrets:
      - name: ghcr-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: catcrawl-col-api
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  selector:
    app: catcrawl-coles-api
  ports:
    - port: 8080
      name: catcrawl-coles-api
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
  externalIPs:
    - 172.16.1.16
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: catcrawl-col-api
  namespace: default
spec:
  host: catcrawl.linds.com.au
  tls:
    secret: linds-certificate-secret
    redirect:
      enable: true
  upstreams:
    - name: catcrawl-coles-api
      service: catcrawl-coles-api
      port: 8080
  routes:
    - path: /
      action:
        proxy:
          upstream: catcrawl-coles-api
          requestHeaders:
            pass: true
          rewritePath: /
          responseHeaders:
            pass:
              - Server