resources:
  # Local resources
  - coredns.yml
  - argocd-servicemonitor.yaml
  - monitoring/alerts.yaml
  - monitoring/alertmanager-config.yaml
  - monitoring/external-secret.yaml

  - nginx/pdf.yml
  - nginx/argocd.yml

  - linds/deploy/deployment.yml
  - linds/deploy/pdf.yml
