apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysctl-rpf-enforcer
  namespace: kube-system
spec:
  selector:
    matchLabels: { app: sysctl-rpf-enforcer }
  template:
    metadata:
      labels: { app: sysctl-rpf-enforcer }
    spec:
      hostNetwork: true
      hostPID: true
      tolerations: [ { operator: "Exists" } ]
      containers:
        - name: enforcer
          image: busybox:1.36
          securityContext: { privileged: true }
          command: [ "sh", "-c", "while true; do for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > $f 2>/dev/null || true; done; sleep 5; done" ]

