apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      nodeSelector:
        datacenter: jd
      containers:
      - name: minecraft
        image: itzg/minecraft-server:latest
        env:
        - name: EULA
          value: "TRUE"
        - name: VERSION
          value: "LATEST"        # or "1.20.1", or "PURPUR", "SPIGOT", "FORGE", etc.
        - name: MEMORY
          value: "4G"           # adjust for your needs
        - name: TYPE
          value: "PAPER"      # or "SPIGOT", "PAPER", etc.
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: jd-nfs-pvc-minecraft
