apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
  annotations:
    argocd-image-updater.argoproj.io/image-list: factorio
    argocd-image-updater.argoproj.io/factorio.update-strategy: latest
